apiVersion: v1
kind: Pod
metadata:
  name: jaeger
spec:
  containers:
  - name: main
    image: docker.io/jaegertracing/jaeger:latest
    ports:
    - name: web
      containerPort: 16686
      hostPort: 16686
    - name: otlp-grpc
      containerPort: 4317
      hostPort: 4317
    - name: otlp-http
      containerPort: 4318
      hostPort: 4318
    env:
    - name: LOG_LEVEL
      value: debug
